[WIP]戦歴の編集
ProgrammingLab/prolab-accounts-client pull request #104
Opened 2019-04-13 01:19 UTC by gedorinku

#38 やる
- [ ] 追加
- [ ] 削除
- [ ] 編集

2019-04-13 10:26 UTC, gedorinku commented
見た目と画像の追加以外はできた

2019-04-13 12:40 UTC, gedorinku commented
close #105

2019-04-14 00:31 UTC, gedorinku commented
@Fukusan64 戦歴のコンポーネント化をここでやってしまったので、とりあえずここまででマージしたい

2019-04-14 02:22 UTC, Fukusan64 requested changes
戦歴を編集したときに保存できたのか分かりにくい
保存を押したときもプレビュー状態になってほしい

2019-04-14 03:00 UTC, Fukusan64 approved these changes
💯

2019-04-14 03:00 UTC, merged