ログアウトできるようになった
ProgrammingLab/prolab-accounts-client pull request #133
Opened 2019-04-15 13:34 UTC by kp54

close #129

2019-04-15 13:55 UTC, gedorinku approved these changes

2019-04-15 14:07 UTC, Fukusan64 requested changes
ロジックの実装は問題ないと思うけど

リンクが叩かれたらstoreのactionを呼ぶだけでも
どこからでも呼べると思うので
ログアウトするためだけのページは作らなくてもいいと思う

2019-04-16 00:35 UTC, kp54 commented
store直殴りでも行けるけど微妙にロジックがあるから全体をモジュールにしたかった

2019-04-16 01:32 UTC, Fukusan64 commented
ページじゃなくてコンポーネントにするでもいいかもしれないと思った

2019-04-16 07:04 UTC, kp54 commented
モジュールに移したのでチェックお願いします
(一応トークンが無効になってるかローカルでチェックはした)

2019-04-16 09:17 UTC, Fukusan64 approved these changes
お疲れ様です
完璧です
💯

2019-04-16 09:17 UTC, merged