Justify height of .achievement
ProgrammingLab/prolab-accounts-client pull request #164
Opened 2019-04-23 06:11 UTC by miyacorata

# Changes
## dlの高さを揃えて溢れるぶんは殺す
* div.achievement にafter疑似要素を設定、non-hoverのときは白グラデがかかる
  * hover時もいい感じのグラデをかけたいけど linear-gradient に transition が効かないのでなんらかの策を考える必要がある
## imgの高さを揃え中央cropする
* object-fit は文明
## 参加メンバー表示位置の変更
* hover時に下ベースで位置を設定した
## 以下蛇足
* 省略した分のdescriptionも全文読めるようにモーダルを出すといいかもしれない？
* a要素の中にa要素は入れてはならない(=HTMLとして適切でない)のもあるので個人的にはモーダル作るのを推したい

2019-04-23 17:21 UTC, miyacorata commented
思ったんすけどスマホには実質hoverという概念がないのでhoverしないと出てこないメンバ一覧実はめっちゃ不親切なのでは

2019-04-24 14:06 UTC, Fukusan64 requested changes
文章を書いたとき、はみ出してしまう
戦歴編集のときは縦横両方
トップページだと横のみはみ出すっぽい
![スクリーンショット_2019-04-24_23-04-37](https://user-images.githubusercontent.com/16333289/56665626-5c15fe80-66e5-11e9-9599-4222b86e9547.png)

2019-04-24 14:06 UTC, Fukusan64 commented
このブランチでする仕事じゃない気もするけど

2019-04-24 16:07 UTC, mucho613 commented
> 思ったんすけどスマホには実質hoverという概念がないのでhoverしないと出てこないメンバ一覧実はめっちゃ不親切なのでは

わかりしかない

2019-04-25 15:42 UTC, miyacorata commented
https://github.com/ProgrammingLab/prolab-accounts-client/pull/164/commits/125374d81f4a3f4df6d6202395c335928fdba2a4 の修正点
* overflow:hidden; した

英文はみ出る問題はそもそもスペースを含まないクソ長いワードを入力していることで発生するので、ここでword-break(overflow-wrap)で改行を強制するのは愚策と判断し修正は加えていません  
(Lorem ipsumぶち込んでひとまず大丈夫そうなのは確認してます)

2019-04-25 16:48 UTC, Fukusan64 approved these changes
完璧だと思う💯

2019-04-26 00:36 UTC, merged