[WIP] ユーザー登録
ProgrammingLab/prolab-accounts-client pull request #65
Opened 2019-03-27 07:25 UTC by kp54

2019-04-01 17:33 UTC, Fukusan64 requested changes
[パスワードの設定をするところ](https://github.com/ProgrammingLab/prolab-accounts-client/pull/65/files#diff-4affa30e1a853b5fee937999cfd92790R10)のあとにパスワードの確認をするinput要素(2回パスワードを打たせて同じものか確認するやつ)を入れてほしい

上の注文のとこ以外は問題ないと思う

2019-04-01 21:35 UTC, kp54 commented
confirmはいらないと思う
どうせコピペするし、ミスってたらリセットすればいい

2019-04-01 21:48 UTC, Fukusan64 commented
そう言われるといらない感もある

2019-04-01 23:57 UTC, gedorinku commented on src/views/Registration.vue
> +        <input required type="password" v-model="password">
User name
Full name
Password
の順で並んでると、chrome(73.0.3683.86)でパスワードを保存する時にfull nameとpasswordを保存しちゃってちょっと困る(safariだとこの順番で並んでても大丈夫だった)

2019-04-02 00:08 UTC, gedorinku commented on src/views/Registration.vue
> +        <input required type="text" v-model="name">
for属性ってこれで使い方あってる?
(inputにidが指定されてないので)
https://developer.mozilla.org/ja/docs/Web/HTML/Element/label#Attributes
@mucho613

2019-04-02 00:08 UTC, gedorinku commented on src/views/Registration.vue
> +      this.createError({ number: 400, message: 'Invalid token' });
これ何が起きても400なのが気になりました

2019-04-02 05:59 UTC, kp54 commented on src/views/Registration.vue
> +        <input required type="password" v-model="password">
id振ったら解消しました

2019-04-02 11:34 UTC, gedorinku commented on src/views/Registration.vue
> +        this.createError({ number: 500, message: 'Something happend' });
`number`にはstatus codeが入る認識なんだけど、`this.tokenVerificationError.response.status` をそのまま入れないのはなぜですか

2019-04-02 11:37 UTC, kp54 commented on src/views/Registration.vue
> +        this.createError({ number: 500, message: 'Something happend' });
たしかに(修正します)

2019-04-02 11:38 UTC, mucho613 commented on src/views/Registration.vue
> +        <input required type="text" v-model="name">
マシンリーダブルな感じにしたいので input にも id を振ってほしい(label と input の対応付けを明示するため)

2019-04-02 12:58 UTC, gedorinku approved these changes

2019-04-02 12:59 UTC, gedorinku commented
close #35

2019-04-02 16:40 UTC, Fukusan64 approved these changes

2019-04-02 16:40 UTC, merged