[WIP]consent/login画面
ProgrammingLab/prolab-accounts-client pull request #9
Opened 2019-01-27 08:43 UTC by gedorinku

#2

2019-01-27 15:02 UTC, Fukusan64 requested changes
ほぼコード見てるだけのレビューなのでアレなんだけど
[ここ](https://github.com/gedorinku/prolab-accounts-client/blob/fdafa91552a6671cb44bb4884e4b15e162604268/src/views/oauth/Login.vue#L29)とかでsrc/components/Error.vueをErrorって定数にimportすると
JavaScriptの基本オブジェクトのErrorと名前がかぶってしまうので
名前を変えたほうが読みやすいと思う

2019-01-28 10:43 UTC, gedorinku commented
@Fukusan64 
直した。
あと、clientのロゴも表示しといた方がいい気がしたので追加した。

2019-01-28 16:59 UTC, Fukusan64 requested changes
[Login.vue#L16](https://github.com/ProgrammingLab/prolab-accounts-client/blob/0087ab569d3fde1833752163b1efc0376c33365e/src/views/oauth/Login.vue#L16)を直すのを忘れてそうです

2019-01-29 01:38 UTC, gedorinku commented
@Fukusan64 なおした

2019-01-29 01:40 UTC, Fukusan64 reviewed
OK

2019-01-29 01:42 UTC, Fukusan64 approved these changes

2019-01-29 01:44 UTC, merged